# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatusManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusEquipamento',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='local',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.StatusManutencao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Departamento'),
            preserve_default=False,
        ),
    ]
