# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161219_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
