# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161218_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='status',
        ),
    ]
