# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Status'),
            preserve_default=False,
        ),
    ]
