# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161218_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_equipamentos', models.ManyToManyField(to='app.Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('profissao', models.CharField(choices=[('0', 'AdmGeral'), ('1', 'AdmDep'), ('2', 'FuncioMan')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Usuario')),
                ('departamento', models.CharField(max_length=200)),
            ],
            bases=('app.usuario',),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default='Usuario', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Usuario'),
            preserve_default=False,
        ),
    ]
