# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161219_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='usuario_ptr',
        ),
        migrations.RemoveField(
            model_name='listas',
            name='lista_equipamentos',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Listas',
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
