# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_auto_20161219_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementolista',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='elementolista',
            name='lista',
        ),
        migrations.DeleteModel(
            name='ElementoLista',
        ),
        migrations.DeleteModel(
            name='ListaEquipamento',
        ),
    ]
