# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_auto_20161219_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default='Fabricante default', max_length=200),
        ),
    ]
