# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0004_auto_20161219_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipamento.Status'),
        ),
    ]
