# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0004_auto_20161219_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.Equipamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.Funcionario')),
            ],
        ),
    ]
